name: Run Python Script

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
        
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 # If you have any dependencies

      - name: Run Geeksforgeeks Python script
        run: python ./script/gfg.py

      - name: Run leetcode Python script
        run: python ./script/leetcode.py

      - name: Run Codeforce Script
        run: python ./script/codeforce.py

      - name: Run CodeChef Script
        run: python ./script/codechef.py

      - name: check readme content
        run: cat README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if [ -n "$(git status --porcelain README.md)" ]; then
            echo "Changes detected"
            git add README.md
            git commit -m "Update README with badges data"
            git push
          else
            echo "No changes detected"
          fi
        # continue-on-error: true
